export const DATA = [
  {
    id: "i0001",
    name: "T-Shirt",
    price: 4,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: {
      src: "img/img-1.jpg",
      alt: "simple white t-shirt",
    },
  },
  {
    id: "i0002",
    name: "Suit",
    price: 200,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: { src: "img/img-2.jpg", alt: "suit" },
  },
  {
    id: "i0003",
    name: "Shirt",
    price: 20,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: { src: "img/img-3.jpg", alt: "shirt" },
  },
  {
    id: "i0004",
    name: "Pants",
    price: 30,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: { src: "img/img-4.jpg", alt: "pants" },
  },
  {
    id: "i0005",
    name: "Scarf",
    price: 5,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: { src: "img/img-5.jpg", alt: "scarfs" },
  },
  {
    id: "i0006",
    name: "Sneakers",
    price: 45,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: { src: "img/img-6.jpg", alt: "sneakers" },
  },
  {
    id: "i0007",
    name: "Blue Jeans",
    price: 30,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: { src: "img/img-7.jpg", alt: "jeans" },
  },
  {
    id: "i0008",
    name: "Boots",
    price: 80,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: { src: "img/img-8.jpg", alt: "boots" },
  },
  {
    id: "i0009",
    name: "Gloves",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: { src: "img/img-9.jpg", alt: "gloves" },
  },
  {
    id: "i0010",
    name: "Hat",
    price: 15,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: { src: "img/img-10.jpg", alt: "hats" },
  },
  {
    id: "i0011",
    name: "Jacket",
    price: 35,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: { src: "img/img-11.jpg", alt: "jacket" },
  },
];
